npm install chalk
npm install chalk-animation
npm install discord.js-selfbot-v13
npm install dotenv
npm install easy-json-database
npm install follow-redirects
npm install fs
npm install fs-extra
npm install gradient-string
npm install nanospinner
npm install uniqid.